//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemDoradczy {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemDoradczy.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aces and Eights.
        /// </summary>
        internal static string Aceseights {
            get {
                return ResourceManager.GetString("Aceseights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternity.
        /// </summary>
        internal static string Alternity {
            get {
                return ResourceManager.GetString("Alternity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ars Magica.
        /// </summary>
        internal static string Arsmagica {
            get {
                return ResourceManager.GetString("Arsmagica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BECMI.
        /// </summary>
        internal static string Becmi {
            get {
                return ResourceManager.GetString("Becmi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big Eyes, Small Mouth.
        /// </summary>
        internal static string Besm {
            get {
                return ResourceManager.GetString("Besm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boot Hill.
        /// </summary>
        internal static string Boothill {
            get {
                return ResourceManager.GetString("Boothill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bushido.
        /// </summary>
        internal static string Bushido {
            get {
                return ResourceManager.GetString("Bushido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Of Cthulu.
        /// </summary>
        internal static string Callofcthulu {
            get {
                return ResourceManager.GetString("Callofcthulu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Champions.
        /// </summary>
        internal static string Champions {
            get {
                return ResourceManager.GetString("Champions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want one that is &quot;cinematic&quot; or has a bit of humor?.
        /// </summary>
        internal static string CinematicQuestion {
            get {
                return ResourceManager.GetString("CinematicQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus on Combat?.
        /// </summary>
        internal static string CombatQuestion {
            get {
                return ResourceManager.GetString("CombatQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conan Mongoose.
        /// </summary>
        internal static string Conanmongoose {
            get {
                return ResourceManager.GetString("Conanmongoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conan TSR.
        /// </summary>
        internal static string Conantsr {
            get {
                return ResourceManager.GetString("Conantsr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CyberPunk 2020.
        /// </summary>
        internal static string Cyberpunk2020 {
            get {
                return ResourceManager.GetString("Cyberpunk2020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D20 Future.
        /// </summary>
        internal static string D20future {
            get {
                return ResourceManager.GetString("D20future", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you like D20? (Skills, feats, etc.).
        /// </summary>
        internal static string D20LikeQuestion {
            get {
                return ResourceManager.GetString("D20LikeQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D20 Modern.
        /// </summary>
        internal static string D20modern {
            get {
                return ResourceManager.GetString("D20modern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D20 Past.
        /// </summary>
        internal static string D20past {
            get {
                return ResourceManager.GetString("D20past", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DC Adventures.
        /// </summary>
        internal static string Dcadventures {
            get {
                return ResourceManager.GetString("Dcadventures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DC Heroes.
        /// </summary>
        internal static string Dcheroes {
            get {
                return ResourceManager.GetString("Dcheroes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DC Universe.
        /// </summary>
        internal static string Dcuniverse {
            get {
                return ResourceManager.GetString("Dcuniverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D&amp;D 0E.
        /// </summary>
        internal static string Dd0e {
            get {
                return ResourceManager.GetString("Dd0e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D&amp;D 1E.
        /// </summary>
        internal static string Dd1e {
            get {
                return ResourceManager.GetString("Dd1e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D&amp;D 4E.
        /// </summary>
        internal static string Dd4e {
            get {
                return ResourceManager.GetString("Dd4e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadlands.
        /// </summary>
        internal static string Deadlands {
            get {
                return ResourceManager.GetString("Deadlands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D&amp;D/TSR derivative or not?.
        /// </summary>
        internal static string DerivativeQuestion {
            get {
                return ResourceManager.GetString("DerivativeQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dresden Files.
        /// </summary>
        internal static string Dresdenfiles {
            get {
                return ResourceManager.GetString("Dresdenfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EarthDawn.
        /// </summary>
        internal static string Earthdawn {
            get {
                return ResourceManager.GetString("Earthdawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eclipse Phase.
        /// </summary>
        internal static string Eclipsephase {
            get {
                return ResourceManager.GetString("Eclipsephase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exhalted.
        /// </summary>
        internal static string Exalted {
            get {
                return ResourceManager.GetString("Exalted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fading Suns.
        /// </summary>
        internal static string Fadingsuns {
            get {
                return ResourceManager.GetString("Fadingsuns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fantasy Hero.
        /// </summary>
        internal static string Fantasyhero {
            get {
                return ResourceManager.GetString("Fantasyhero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Science fiction or Science fantasy?.
        /// </summary>
        internal static string FOrFQuestion {
            get {
                return ResourceManager.GetString("FOrFQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FUDGE.
        /// </summary>
        internal static string Fudge {
            get {
                return ResourceManager.GetString("Fudge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D20 based or D20 lite?.
        /// </summary>
        internal static string FullLiteQuestion {
            get {
                return ResourceManager.GetString("FullLiteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you fundamentalist about it?.
        /// </summary>
        internal static string FundamentalistQuestion {
            get {
                return ResourceManager.GetString("FundamentalistQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamma World.
        /// </summary>
        internal static string Gammaworld {
            get {
                return ResourceManager.GetString("Gammaworld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gangbusters.
        /// </summary>
        internal static string Gangbusters {
            get {
                return ResourceManager.GetString("Gangbusters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want some other genres mixed with that?.
        /// </summary>
        internal static string GenresMixedQuestion {
            get {
                return ResourceManager.GetString("GenresMixedQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gothic, Space Opera or Post Apocalyptic?.
        /// </summary>
        internal static string GothicQuestion {
            get {
                return ResourceManager.GetString("GothicQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GURPS.
        /// </summary>
        internal static string Gurps {
            get {
                return ResourceManager.GetString("Gurps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GURPS Fallout.
        /// </summary>
        internal static string Gurpsfallout {
            get {
                return ResourceManager.GetString("Gurpsfallout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GURPS Mecha.
        /// </summary>
        internal static string Gurpsmech {
            get {
                return ResourceManager.GetString("Gurpsmech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GURPS Supers.
        /// </summary>
        internal static string Gurpssupers {
            get {
                return ResourceManager.GetString("Gurpssupers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you think of Gygax?.
        /// </summary>
        internal static string GygaxQuestion {
            get {
                return ResourceManager.GetString("GygaxQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hackmaster.
        /// </summary>
        internal static string Hackmaster {
            get {
                return ResourceManager.GetString("Hackmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hachmaster Basaic.
        /// </summary>
        internal static string Hackmasterb {
            get {
                return ResourceManager.GetString("Hackmasterb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harnmaster.
        /// </summary>
        internal static string Harnmaster {
            get {
                return ResourceManager.GetString("Harnmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have wads of cash for minis?.
        /// </summary>
        internal static string HaveCashQuestion {
            get {
                return ResourceManager.GetString("HaveCashQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HERO.
        /// </summary>
        internal static string Hero {
            get {
                return ResourceManager.GetString("Hero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hollow Earth Expedition.
        /// </summary>
        internal static string Hollowearthexpedition {
            get {
                return ResourceManager.GetString("Hollowearthexpedition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiw tailored do you want your &quot;universal&quot; system?.
        /// </summary>
        internal static string HowTailoredQuestion {
            get {
                return ResourceManager.GetString("HowTailoredQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humor, Spies or Cyberpunk?.
        /// </summary>
        internal static string HSCQuestion {
            get {
                return ResourceManager.GetString("HSCQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hybridize it moreso with D&amp;D?.
        /// </summary>
        internal static string HybridizeItQuestion {
            get {
                return ResourceManager.GetString("HybridizeItQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICONS.
        /// </summary>
        internal static string Icons {
            get {
                return ResourceManager.GetString("Icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just do a web search ;-).
        /// </summary>
        internal static string Justdoaweb {
            get {
                return ResourceManager.GetString("Justdoaweb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend of the 5 Rings.
        /// </summary>
        internal static string Loft5r {
            get {
                return ResourceManager.GetString("Loft5r", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marvel Super-Heroes (FASERIP).
        /// </summary>
        internal static string Marvelsuper {
            get {
                return ResourceManager.GetString("Marvelsuper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marvel Universe.
        /// </summary>
        internal static string Marveluniverse {
            get {
                return ResourceManager.GetString("Marveluniverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is du/dx = cu+xy?.
        /// </summary>
        internal static string MathQuestion {
            get {
                return ResourceManager.GetString("MathQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mechwarrior.
        /// </summary>
        internal static string Mechwarrior {
            get {
                return ResourceManager.GetString("Mechwarrior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metamorphosis Alpha.
        /// </summary>
        internal static string Metamorphosisalpha {
            get {
                return ResourceManager.GetString("Metamorphosisalpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Based on a Movie or TV show?.
        /// </summary>
        internal static string MTVQuestion {
            get {
                return ResourceManager.GetString("MTVQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mutants and Masterminds.
        /// </summary>
        internal static string Mutantsandman {
            get {
                return ResourceManager.GetString("Mutantsandman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mythology based?.
        /// </summary>
        internal static string MysthologyQuestion {
            get {
                return ResourceManager.GetString("MysthologyQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have a niche genre in mind?.
        /// </summary>
        internal static string NicheGenreQuestion {
            get {
                return ResourceManager.GetString("NicheGenreQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a subgenre.
        /// </summary>
        internal static string OAHQuestion {
            get {
                return ResourceManager.GetString("OAHQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old or new school?.
        /// </summary>
        internal static string OldNewQuestion {
            get {
                return ResourceManager.GetString("OldNewQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open D6.
        /// </summary>
        internal static string Opend6 {
            get {
                return ResourceManager.GetString("Opend6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want an &quot;open&quot; game.
        /// </summary>
        internal static string OpenGameFutureQuestion {
            get {
                return ResourceManager.GetString("OpenGameFutureQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want an &quot;open&quot; game?.
        /// </summary>
        internal static string OpenGameQuestion {
            get {
                return ResourceManager.GetString("OpenGameQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oriental Adventures.
        /// </summary>
        internal static string Oriental {
            get {
                return ResourceManager.GetString("Oriental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paranoia.
        /// </summary>
        internal static string Paranoia {
            get {
                return ResourceManager.GetString("Paranoia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you like point buy character gen?.
        /// </summary>
        internal static string PointBuyQuestion {
            get {
                return ResourceManager.GetString("PointBuyQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you like races as classes?.
        /// </summary>
        internal static string RacesAsClassesQuestion {
            get {
                return ResourceManager.GetString("RacesAsClassesQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Based on real comics?.
        /// </summary>
        internal static string RealComicsQuestion {
            get {
                return ResourceManager.GetString("RealComicsQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really?.
        /// </summary>
        internal static string ReallyQuestion {
            get {
                return ResourceManager.GetString("ReallyQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RIFTS.
        /// </summary>
        internal static string Rifts {
            get {
                return ResourceManager.GetString("Rifts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risus.
        /// </summary>
        internal static string Risus {
            get {
                return ResourceManager.GetString("Risus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robotech.
        /// </summary>
        internal static string Robotech {
            get {
                return ResourceManager.GetString("Robotech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolemaster.
        /// </summary>
        internal static string Rolemaster {
            get {
                return ResourceManager.GetString("Rolemaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RuneQuest.
        /// </summary>
        internal static string Runequest {
            get {
                return ResourceManager.GetString("Runequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Savage Worlds.
        /// </summary>
        internal static string Savageworlds {
            get {
                return ResourceManager.GetString("Savageworlds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semi-historical setting?.
        /// </summary>
        internal static string SemiHistoricalQuestion {
            get {
                return ResourceManager.GetString("SemiHistoricalQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadowrun.
        /// </summary>
        internal static string Shadowrun {
            get {
                return ResourceManager.GetString("Shadowrun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Still want a slew of skills.
        /// </summary>
        internal static string SlewOrSkillsQuestion {
            get {
                return ResourceManager.GetString("SlewOrSkillsQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old or new school?.
        /// </summary>
        internal static string SpiesQuestion {
            get {
                return ResourceManager.GetString("SpiesQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spirit of the Century.
        /// </summary>
        internal static string Spiritofthecentury {
            get {
                return ResourceManager.GetString("Spiritofthecentury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spycraft.
        /// </summary>
        internal static string Spycraft {
            get {
                return ResourceManager.GetString("Spycraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star Frontiers.
        /// </summary>
        internal static string Starfrontiers {
            get {
                return ResourceManager.GetString("Starfrontiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star Wars D6.
        /// </summary>
        internal static string Starwarsd6 {
            get {
                return ResourceManager.GetString("Starwarsd6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have lots of D6s and don&apos;t care about episodes 1-3.
        /// </summary>
        internal static string StarWarsQuestion {
            get {
                return ResourceManager.GetString("StarWarsQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star Wars SAGA.
        /// </summary>
        internal static string Starwarssaga {
            get {
                return ResourceManager.GetString("Starwarssaga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mix in some steampunk?.
        /// </summary>
        internal static string SteamPunkQuestion {
            get {
                return ResourceManager.GetString("SteamPunkQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supernatural or pulp?.
        /// </summary>
        internal static string SupernaturalPulpQuestion {
            get {
                return ResourceManager.GetString("SupernaturalPulpQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want a diceless system or one with lots of online fantasies?.
        /// </summary>
        internal static string SystemQuestion {
            get {
                return ResourceManager.GetString("SystemQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Secret.
        /// </summary>
        internal static string Topsecret {
            get {
                return ResourceManager.GetString("Topsecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TORG.
        /// </summary>
        internal static string Torg {
            get {
                return ResourceManager.GetString("Torg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traveller.
        /// </summary>
        internal static string Traveller {
            get {
                return ResourceManager.GetString("Traveller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True20.
        /// </summary>
        internal static string True20 {
            get {
                return ResourceManager.GetString("True20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunnels and Trolls.
        /// </summary>
        internal static string Tunnelstrolls {
            get {
                return ResourceManager.GetString("Tunnelstrolls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like Undead?.
        /// </summary>
        internal static string UndeadQuestion {
            get {
                return ResourceManager.GetString("UndeadQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Still want a &quot;universal&quot; system?.
        /// </summary>
        internal static string UniversalSystemQuestion {
            get {
                return ResourceManager.GetString("UniversalSystemQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to finance a store dedicated to 1 game?.
        /// </summary>
        internal static string WantFinanceStoreQuestion {
            get {
                return ResourceManager.GetString("WantFinanceStoreQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warhammer.
        /// </summary>
        internal static string Warhammer {
            get {
                return ResourceManager.GetString("Warhammer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warhammer 40k RPG.
        /// </summary>
        internal static string Warhammer40krpg {
            get {
                return ResourceManager.GetString("Warhammer40krpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s time to choose a game to play isn&apos;t it? My magic software will handle the decision making for you. Just click the buttons, and watch the magic being done! Enjoy ;-).
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FATE based, D20 based or neither?.
        /// </summary>
        internal static string WhatBasedQuestion {
            get {
                return ResourceManager.GetString("WhatBasedQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old school, D&amp;D 2E, 3E or 4E based?.
        /// </summary>
        internal static string WhatEQuestion {
            get {
                return ResourceManager.GetString("WhatEQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D6s, D10s or D20?.
        /// </summary>
        internal static string WhichDQuestion {
            get {
                return ResourceManager.GetString("WhichDQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s start which something simple. Which genre interests you?.
        /// </summary>
        internal static string WhichGenreQuestion {
            get {
                return ResourceManager.GetString("WhichGenreQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which sub-genre?.
        /// </summary>
        internal static string WhichSubGenreQuestion {
            get {
                return ResourceManager.GetString("WhichSubGenreQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With classes? Point Buy?.
        /// </summary>
        internal static string WithClassesQuestion {
            get {
                return ResourceManager.GetString("WithClassesQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With meta-plots and a CCG element?.
        /// </summary>
        internal static string WithMetaPlotsQuestion {
            get {
                return ResourceManager.GetString("WithMetaPlotsQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World of Darkness.
        /// </summary>
        internal static string Worldofdarkness {
            get {
                return ResourceManager.GetString("Worldofdarkness", resourceCulture);
            }
        }
    }
}
